spring.application.name=digitalCitizen
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@senior_low?TNS_ADMIN=/Users/shreyashrestha/wallet
spring.datasource.username=ADMIN
spring.datasource.password=QWEasd123456789
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


