spring.application.name=digitalCitizen
server.port=8080

python.api.base=${PYTHON_API_BASE:https://dicurecitizen-ml.onrender.com}      
risk.lowMax=${RISK_LOW_MAX:0.10}
risk.highMin=${RISK_HIGH_MIN:0.70}

spring.datasource.url=jdbc:oracle:thin:@senior_low?TNS_ADMIN=/etc/secrets
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


